# Generated by Django 4.1.2 on 2022-10-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('card', models.TextField()),
                ('account', models.TextField()),
                ('account_valid_to', models.TextField()),
                ('client', models.TextField()),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('patronymic', models.TextField()),
                ('date_of_birth', models.TextField()),
                ('passport', models.TextField()),
                ('passport_valid_to', models.TextField()),
                ('phone', models.TextField()),
                ('oper_type', models.CharField(choices=[(1, 'Пополнение'), (2, 'Снятие'), (3, 'Оплата')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('oper_result', models.CharField(choices=[(1, 'Отказ'), (2, 'Успешно')], max_length=7)),
                ('terminal', models.TextField()),
                ('terminal_type', models.CharField(choices=[(1, 'POS'), (2, 'ATM')], max_length=3)),
                ('city', models.TextField()),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name': 'Тразнакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
