# Generated by Django 4.1.2 on 2022-10-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_transaction_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('description', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Паттерн',
                'verbose_name_plural': 'Паттерны',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='patterns',
            field=models.ManyToManyField(to='app.pattern'),
        ),
    ]
